import keyMirror  from 'key-mirror';

export default keyMirror({
  GET_SHIPMENTS: null,
  GET_SHIPMENTS_SUCCESS: null,
  GET_SHIPMENTS_FAILURE: null,
  GET_SHIPMENT: null,
  GET_SHIPMENT_SUCCESS: null,
  GET_SHIPMENT_FAILURE: null,
  POST_SHIPMENT:null,
  POST_SHIPMENT_SUCCESS: null,
  POST_SHIPMENT_FAILURE: null,
  DELETE_SHIPMENT: null,
  DELETE_SHIPMENT_SUCCESS: null,
  DELETE_SHIPMENT_FAILURE: null,
  VIEW_SHIPMENT_RESET: null,
  POST_SHIPMENT_RESET: null
});